swagger: '2.0'
info:
  title: Neo Portfolio
  version: v1
basePath: /api/v1
paths:
  /posts:
    get:
      summary: Post list
      tags:
        - Post
      produces:
        - application/json
      responses:
        200:
          description: On Success
          schema:
            $ref: '#/definitions/Responses/Posts'
    post:
      summary: Create Post
      tags:
        - Post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Parameter/Post"
      responses:
        200:
          description: On Success
          schema:
            $ref: "#/definitions/Responses/Post"
          examples:
            application/json:
              status: SUCCESS
              data:
                id: 1
                title: テスト
                description: これはテストの本文です。
        400:
          description: Bad Request
          schema:
            type: object
            required:
              - status
              - error
              - exception
            properties:
              status:
                type: integer
              error:
                type: string
              exception:
                type: string
          examples:
            application/json:
              status: 400
              error: Bad Request
              exception: param is missing or the value is empty
  /post/{postId}:
    get:
      summary: Show Post
      tags:
        - Post
      produces:
        - application/json
      parameters:
        - name: postId
          in: path
          description: 参照したいpostのid
          required: true
          schema:
            type: integer
      responses:
        200:
          description: On Success
          schema:
            $ref: '#/definitions/Responses/Post'
    delete:
      summary: Delete Post
      tags:
        - Post
      produces:
        - application/json
      parameters:
        - name: postId
          in: path
          description: 削除したいpostのid
          required: true
          schema:
            type: integer
      responses:
        200:
          description: On Success
          examples:
            application/json:
              status: SUCCESS
    put:
      summary: Update Post
      tags:
        - Post
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Parameter/Post"
      responses:
        200:
          description: On Success
          schema:
            $ref: "#/definitions/Responses/Post"
          examples:
            application/json:
              status: SUCCESS
              data:
                id: 1
                title: ポートフォリオ
                description: これはポートフォリオの本文です。
        400:
          description: Bad Request
          schema:
            type: object
            required:
              - status
              - error
              - exception
            properties:
              status:
                type: integer
              error:
                type: string
              exception:
                type: string
          examples:
            application/json:
              status: 400
              error: Bad Request
              exception: param is missing or the value is empty
definitions:
  Parameter:
    Post:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          description: postのタイトル
          example: ポートフォリオ
        description:
          type: string
          description: postの本文
          example: これはポートフォリオの本文です。
  Responses:
    Posts:
      type:  array
      items:
        $ref: '#/definitions/Responses/Post'
    Post:
      type: object
      required:
        - title
        - description
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          description: postのタイトル
          example: ポートフォリオ
        description:
          type: string
          description: postの本文
          example: これはポートフォリオの本文です。
        created_at:
          type: string
          description: 作成日時
          example: '2020-12-08T16:44:18.843Z'
        updated_at:
          type: string
          description: 更新日時
          example: '2020-12-08T16:44:18.843Z'